version: "3.9"
services:
    ftx_lending:
        build: ./
        volumes:
            - .:/home
        ports:
            - "27017:27017"
        command: bash -c "
                        python telegram_bot/add_id.py &&
                        python main.py &&
                        cron -f"
        tty: true
